<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<!--Barre de navigation-->

<body>
<header>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid ms-3">
    <a class="navbar-brand" href="#">Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Accueil</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Liste des articles</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">S'inscrire / Se connecter</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Mon profil</a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="#">Ajouter un article</a>
        </li>
      
      </ul>
      <form class="d-flex">
        <input class="form-control me-3" type="search" placeholder="Rechercher un article" aria-label="Search">
        <button class="btn btn-outline-danger" type="submit">Rechercher</button>
      </form>
    </div>
  </div>
</nav>  
</header>



<!-- Template de la page -->

<main class="container">
<?php require $template . '.phtml' ?>
</main>


<!--Footer-->
<footer class="bg-light text-dark pt-5 pb-4">
    <div class="container text-center text-md-left">
        <div class="row text-center text-md-left">
            <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
                <h5 class="text-uppercase mb-4 font-weight-bold text-danger">A propos</h5>
                <hr class="mb-4">
                <p class="text-start">Lorem ipsum dolor, sit amet consectetur adipisicing elit. <br>Consectetur fugiat autem neque numquam quaerat ipsam magnam voluptatibus, 
                    pariatur modi voluptates sapiente laboriosam asperiores possimus. 
                    Enim ipsam nam odit, corporis delectus odio dolore at laudantium eos illo, officia 
                    impedit doloremque exercitationem!
                </p>
            </div>
            <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
                <h5 class="text-uppercase mb-4 font-weight-bold text-danger">S'abonner à la newsletter</h5>
                <hr class="mb-4">

                <form>
                    <div class="mb-3">
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Renseigner une adresse e-mail valide">
                     </div>
                    <button type="submit" class="btn btn-danger">Souscrire</button>
                </form>
            </div>
                <div class="col-md-6 col-lg-3 col-xl-3 mx-auto mt-3 ">
                <h5 class="text-uppercase mb-4 font-weight-bold text-danger">Contact</h5>
                <hr class="mb-4">
                <p>
                    <li class="fas fa-envelope me-3"></li>blog@webforce.fr
                </p>
                <p>
                    <li class="fas fa-phone-alt me-2"></li>+33 7 20 20 20
                </p>
                <p>
                    <li class="fas fa-home me-2"></li> Strasbourg, France
                </p>
            </div>

            <div class="row d-flex justify-content-center">
                <div>
                    <p>
                    © 2021 <strong class="text-danger">La Team WF3.</strong>
                    </p>
                </div>
            </div>
            <div class="row d-flex justify-content-center">
                <div class="text-center">
                    <ul class="list-unstyled list-inline">
                        <li class="list-inline-item">
                            <a href="#" class="text-dark"><li class="fab fa-facebook"></li></a>   
                        </li>
                        <li class="list-inline-item">
                            <a href="#" class="text-dark"><li class="fab fa-twitter"></li></a>   
                        </li>
                        <li class="list-inline-item">
                            <a href="#" class="text-dark"><li class="fab fa-instagram"></li></a>   
                        </li>
                        <li class="list-inline-item">
                            <a href="#" class="text-dark"><li class="fab fa-pinterest"></li></a>   
                        </li>
                        <li class="list-inline-item">
                            <a href="#" class="text-dark"><li class="fab fa-linkedin"></li></a>   
                        </li>
                    </ul>
                </div>

        </div>

    </div>

</footer>






</body>
</html>