<h1>Se connecter à son compte</h1>

<form action="blog_login.php" method="post">
	<?php if (isset($_SESSION['error'])): ?>
		<aside class="alert alert-danger">
			<?= $_SESSION['error'] ?>
			<!-- Suppression de l'erreur stockée après l'avoir affichée -->
			<?php unset($_SESSION['error']) ?>
		</aside>
	<?php endif ?>

<div class="row g-2">
  <div class="col-md">
    <div class="form-floating">
        <label for="username">Taper votre Nom</label>
		<input type="text" name="username" id="nom" class="form-control">
    </div>
  </div>
  <div class="col-md">
    <div class="form-floating">
        <label for="password">Mot de passe</label>
        <input type="password" name="password" class="form-control" id="password">
    </div>
  </div>
    <div class="mt-3">
	    <button class="btn btn-primary">Connexion</button>
    </div>
</div>

</form>