

<form action="edit_article.php" method="post" enctype="multipart/form-data" class="w-75 ">
<input type="hidden" name="id" value=" <?= $edit['id']  ?>"/>
<div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Titre</label>
  <input type="text" class="form-control" id="exampleFormControlInput1"name="titre" placeholder="titre" value="<?= $edit['titre']  ?> " required>
</div>
<div class="mb-3">
  <label for="exampleFormControlTextarea1" class="form-label">Contenu</label>
  <textarea class="form-control" id="exampleFormControlTextarea1" name="contenu" type="text" rows="3"  required> <?= $edit['contenu']  ?> </textarea>
</div>
<div class="mb-3 row">

<div class="col">
    <label for="validationDefault04" class="form-label">Categorie</label>
    <select class="form-select " id="validationDefault04" name="categorie" >
        <option selected value=" <?= $default_categorie['id'] ?> "><?= $default_categorie['nom'] ?> <option>
      <?php foreach($categories as $categorie): ?>
        <option value="<?= $categorie['id'] ?>" ><?= $categorie['nom']; ?></option>
      <?php   endforeach  ?>
    </select>
  </div>

  <div class="col-md">
  <label for="formFileLg" class="form-label">Image article</label>
  <input class="form-control form-control-lg" id="formFileLg" type="file" name="file"  required>
</div>
</div>
  
<div class="col-12 mt-3">
    <button class="btn btn-primary" type="submit" name="submit">Enregister la modification</button>
  </div>
</div>
</form>
