<h1 class="mt-4">Se connecter à son compte</h1>

<form action="login.php" method="post">
	<?php if (isset($_SESSION['error'])): ?>
		<aside class="alert alert-danger">
			<?= $_SESSION['error'] ?>
			<!-- Suppression de l'erreur stockée après l'avoir affichée -->
			<?php unset($_SESSION['error']) ?>
		</aside>
	<?php endif ?>

<div class="row g-2 ">
  <div class="col-md">
    <div class="form-group">
        <label for="nom">Votre nom : </label>
		<input type="text" name="username" id="nom" class="form-control" placeholder="Taper votre nom">
    </div>
  </div>
  <div class="col-md">
    <div class="form-group">
        <label for="password"></label>
        <input type="password" name="password" class="form-control" id="password" placeholder="Taper votre mot de passe">
    </div>
  </div>
    <div class="mt-3">
	    <button class="btn btn-primary">Connexion</button>
    </div>
</div>

</form>