<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="./assets/profil.css">
</head>


<body>

<div class="row py-5 px-4">
    <div class="col-md-8 mx-auto mt-3 mb-3">
        <div class="bg-white shadow rounded overflow-hidden">
            <div class="px-4 pt-0 pb-4 cover">
                <div class="media align-items-end profile-head mb-5">
                    <div class="profile mr-3 mb-3"><img src="../img/150.png" alt="..." width="130" class="rounded mb-2 img-thumbnail"></div>
                    <div class="media-body  text-black">
                      <h4 class="mt-0 pb-5"><?= $infosUser['nom']?> <?= $infosUser['prenom']?></h4>
                    </div>
                </div>
          </div>
            
            <div class="px-4 py-3">
                <h5 class="text-danger mt-2 mb-2">Bio'</h5>
                <div class="p-4 rounded shadow-sm bg-light">
                    <p class="font-italic mb-0">Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                    <p class="font-italic mb-0">Lorem ipsum dolor sit.</p>
                    <p class="font-italic mb-0">Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut libero quos esse.r</p>
                </div>
            </div>
            <div class="px-4 py-3">
                <h5 class="text-danger mb-2">Coordonnées</h5>
                <div class="p-4 rounded">
                    <p class="font-italic mb-0"><?= $infosUser['email']?></p>
                </div>
            </div>
            <div class="py-4 px-4">
                <div class="d-flex align-items-center justify-content-between mb-3">
                    <h5 class="text-danger mb-2">Derniers articles</h5><a href="#" class="btn btn-link text-muted">Montrer tous les articles</a>
                </div>
                <div class="row">
                    <div class="col-lg-6 mb-2 pr-lg-1"><img src="https://via.placeholder.com/450x350" alt="" class="img-fluid rounded shadow-sm">
                  
                    </div>
                    <div class="col-lg-6 mb-2 pl-lg-1"><img src="https://via.placeholder.com/450x350" alt="" class="img-fluid rounded shadow-sm"></div>
                    <div class="col-lg-6 pr-lg-1 mb-2"><img src="https://via.placeholder.com/450x350" alt="" class="img-fluid rounded shadow-sm"></div>
                    <div class="col-lg-6 pl-lg-1"><img src="https://via.placeholder.com/450x350" alt="" class="img-fluid rounded shadow-sm"></div>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>
